spring:
  application:
    name: connecple_backend
  datasource:
    url: ${CONNECPLE_DB_URL}
    username: ${CONNECPLE_DB_USERNAME}
    password: ${CONNECPLE_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

admin:
  id: admin
  password: 1234

aws:
  s3:
    bucket-name: ${BUCKET-NAME}
    access-key: ${BUCKET-ACCESS-KEY}
    secret-key: ${BUCKET-SECRET-KEY}
    region: ${BUCKET-REGION}
