spring:
  application:
    name: connecple_backend
  config:
    import: classpath:/properties/env.properties
  datasource:
    url: ${CONNECPLE_DB_URL}
    username: ${CONNECPLE_DB_USERNAME}
    password: ${CONNECPLE_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

admin:
  id: admin
  password: 1234

aws:
  s3:
    bucket-name: ${BUCKET_NAME}
    access-key: ${BUCKET_ACCESS_KEY}
    secret-key: ${BUCKET_SECRET_KEY}
    region: ${BUCKET_REGION}
